title: Tran Gia Han DINH
logo: /profil.png
description: |
  ğŸ“ Ã‰tudiante en Master dâ€™IngÃ©nierie en Data Science for Social Sciences Ã  lâ€™UniversitÃ© Paris Nanterre.
  

  Je suis capable dâ€™analyser et visualiser des donnÃ©es dans les domaines de lâ€™Ã©conomie, la finance et les statistiques.
  
  
  Actuellement en recherche dâ€™une alternance de 2 ans dÃ¨s septembre 2025 (2j entreprise / 3j Ã©cole, puis 100â€¯% entreprise).
show_download: true
theme: jekyll-theme-minimal
